stages:
  - build
  - deploy

# Etapa de construcción
build:
  stage: build
  image: maven:3.8.1-jdk-11  # Imagen Docker con Maven y JDK 11
  script:
    - echo "Compilando el proyecto..."
    - mvn clean install -DskipTests  # Realiza la compilación del proyecto
  only:
    - main
    - Testing  # Esto asegura que solo se ejecute cuando se realicen cambios en las ramas 'main' o 'Testing'

# Etapa de despliegue
deploy:
  stage: deploy
  image: node:16  # Imagen de Node.js para hacer el despliegue
  script:
    - echo "Desplegando la aplicación..."
    - npm install  # Instala dependencias de Node
    - npm run build  # Construye la aplicación para producción
    - git push https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Josue_Palomino/Avance_Final.git  # Despliega el proyecto
  only:
    - Testing  # Asegura que el despliegue solo se realice en la rama 'main'
