#Este archivo puede ser similar al de CI pero con pasos adicionales para desplegar el código
name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Despliega cuando se hace push a la rama `main`.
      - Testing

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usamos Ubuntu para el despliegue.

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4  # Usamos la versión más reciente de `checkout`.

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Empaquetar y construir la aplicación
        run: mvn clean install -DskipTests

      - name: Desplegar a Vercel
        uses: amondnet/vercel-action@v20  # Usamos la acción de
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Token de Vercel almacenado en secretos.
          vercel-args: '--prod'  # Despliega en producción.
          working-directory: '.'  # Directorio de trabajo, ajusta si es necesario.